apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/data-science-persistent-volumes/kubeflow/kubeflow-pipeline-mysql-pv
    server: 10.10.10.10
  storageClassName: nfs-client

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: nfs-client
  volumeName: pipeline-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
