# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pipeline-pv
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   nfs:
#     path: /home/davit/kubeflow-pipeline-mysql-pv
#     server: 127.0.0.1
#   storageClassName: nfs-client

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pv-claim
# spec:
#   storageClassName: nfs-client
#   volumeName: pipeline-pv
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kfp-mysql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/davit/kubeflow-kfp-mysql-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  volumeName: kfp-mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gpu1