# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: minio-pv
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   nfs:
#     path: /home/davit/kubeflow-minio-pv
#     server: 127.0.0.1
#   storageClassName: nfs-client

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: minio-pvc
# spec:
#   storageClassName: nfs-client
#   volumeName: minio-pv
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi


apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/davit/kubeflow-minio-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  storageClassName: manual
  volumeName: minio-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
